v2 relax ruamel.yaml, prompt-toolkit, cryptography
relax ruamel.yaml, prompt-toolkit, cryptography because it was messing up with OpenSSL

```py
OpenSSL/SSL.py", line 267, in X509VerificationCodes
AttributeError: module 'lib' has no attribute 'X509_V_ERR_UNABLE_TO_GET_ISSUER_CERT'
```